.github/workflows/ci.yml, package.json
This PR is fixing the regular deployment of the toolbox - you can see it working here https://toolbox.dev.orfium.xyz/
=> fix: deployment to s3

.github/workflows/combine-prs.yml
Replace dependabot workflow with [this](https://github.com/Orfium/orfium-github-actions#fe-combine-dependabot-prs) one.
Ticket: [DEV-47](https://orfium.atlassian.net/browse/DEV-47)
=> [DEV-47] Feat/use dependabot workflow from shared repo

documentation/docs/api/index.md, documentation/docs/api/interfaces/AxiosPromise.md, documentation/docs/api/interfaces/AxiosRequestConfig.md, documentation/docs/api/interfaces/AxiosStatic.md, documentation/docs/api/modules.md, documentation/docs/api/namespaces/_category_.yml, documentation/docs/api/namespaces/auth.md, documentation/docs/modules/authentication.md, documentation/docs/modules/request.md, documentation/docs/modules/routing.md, package.json, src/authentication/authentication.test.tsx, src/authentication/config.ts, src/authentication/context.tsx, src/authentication/index.ts, src/authentication/types.ts, src/index.ts, src/request/request.test.ts, yarn.lock
This PR introduces the Authentication module. It's an abstraction of auth0 react package that provides the minimum functions that we might need and the allows for overrides on the Provider config.
Ticket: [DEV-39](https://orfium.atlassian.net/browse/DEV-39)
Tested that our handling on the package works as expected.
√ renders without crashing 
√ renders the test component 
√ redirects to login if not authenticated 
√ renders the loading while its authenticating
=> [DEV-39] feat: authentication folder

.github/workflows/ci.yml, package.json
This PR adds the automatic releases to npm with semantic
=> feat: adding automatic releases with npm and semantic

package.json, sonar-project.properties
This PR introduce sonarqube to the project
=> feat: adding sonarqube to the project

.github/workflows/teardown-review-app.yml
Adds the reusable teardown workflow.
=> feat: add teardown workflow

documentation/docs/intro.md, documentation/docs/maintenance.md, documentation/docs/modules/Authentication/TopBar.md, documentation/docs/modules/Authentication/authentication.md, documentation/docs/modules/Authentication/faq.md, documentation/docs/modules/Authentication/flow.md, documentation/docs/modules/Request/migration.md, documentation/docs/modules/Request/orfiumSSO.md, documentation/docs/modules/Request/request.md, documentation/docs/modules/routing.md
Did some proof-reading of the existing documentation and updated it accordingly, in order for it to be more concise and easily readable.
Also updated a section of the Authentication module that wasn't required.
=> refactor: update documentation

src/index.ts
This PR fixes the exportation of all the things from index but specifically the `useOrganization`
=> fix: exports for useOrganization and others

.github/workflows/pr.yml, .github/workflows/teardown-review-app.yml
In this PR we add a check if the pr contains the label dependencies, then we mustn't create a Review App and we shouldn't delete as well
tickets:
[orfium.atlassian.net/browse/FE-26](https://orfium.atlassian.net/browse/FE-26)
[orfium.atlassian.net/browse/DEVOPS-800](https://orfium.atlassian.net/browse/DEVOPS-800)
=> [FE-26] [DEVOPS-800] Feat/ Disable Dependabot Review Apps

environments/common.env, environments/review.env
PR of shame. Missing env file for reusable review workflow.
=> [FE-26] Fix/ env file for review apps

package.json
do not run when package is installed
=> fix: run husky on prepare

package.json
=> fix: move react-error-boundary to deps

package.json
=> fix: make builds serial

__mocks__/@auth0/auth0-spa-js.ts, src/authentication/context.tsx
This PR solves the problem of adblockers or safari blocking our SSO
=> [DVP-125] fix: adding exlicit cachelocation for bypassing adblockers

src/authentication/components/TopBar/TopBar.test.tsx, src/authentication/components/TopBar/TopBar.tsx
=> fix: hide selected organization from organization switcher drop-down [DVP-131]

.github/workflows/ci.yml, .github/workflows/pr.yml, .github/workflows/sonar.yml
This PR tends to solve issues with errors/warnings on semantic-release need to use LTS node version
https://github.com/Orfium/toolbox/actions/runs/6311779958/job/17136464976
=> fix: add latest node LTS and fix warnings

src/ui/Navigation/components/Drawer/Navigation/Navigation.styles.ts, src/ui/Navigation/components/Drawer/Navigation/Navigation.tsx
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request introduces a new navigation component with a styled container and menu items. The navigation component uses the `react-router-dom` to match the current path and initialize the expanded status of the dropdowns. 
> 
> ## What changed
> Three new files were added:
> - `Navigation.styles.ts`: This file contains the styled components for the navigation container. It includes CSS for transitions, background color, box-sizing, flex properties, overflow, padding, and text wrapping.
> - `Navigation.tsx`: This file is the main navigation component. It uses the `react-router-dom` to match the current path and initialize the …
=> feat: implement a navigational menu wrapper component

src/ui/Navigation/Navigation.styles.tsx, src/ui/Navigation/Navigation.tsx, src/ui/Navigation/common.styles.ts, src/ui/Navigation/components/Drawer/Drawer.styles.ts, src/ui/Navigation/components/Drawer/Drawer.tsx, src/ui/Navigation/components/Drawer/Navigation/Navigation.styles.ts, src/ui/Navigation/components/Drawer/Navigation/Navigation.tsx, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.styles.ts, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.tsx, src/ui/Navigation/index.ts, src/ui/Navigation/types.ts, src/ui/consts.ts, src/ui/index.ts
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request includes various changes to the codebase related to navigation and styling. It introduces new styled components, imports external libraries, and adds authentication-related functions and configurations. It also defines a React component called "Navigation" that renders a navigation menu based on the current URL and user role. Additionally, it includes changes to file structure and exports/imports of components and props.
> 
> ## What changed
> - Added styles for a navigation component, including wrapper, global navigation, and single icon container
> - Added styled components for creating a container for icons, …
=> feat: Implement the exported navigation component

documentation/docs/api/interfaces/AxiosRequestConfig.md, documentation/docs/api/interfaces/AxiosStatic.md, documentation/docs/api/modules.md, src/ui/Navigation/Navigation.tsx, src/ui/Navigation/components/ClientSelector/ClientSelector.tsx, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.tsx, src/ui/TopBar/components/UserMenu/UserMenu.tsx
Explicitly pass the `theme` prop to styled components, in order to avoid testing issues with consumers that use vitest
[DSTRBTN-540]: https://orfium.atlassian.net/browse/DSTRBTN-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: explicitly pass theme prop to styled components

src/authentication/index.ts, src/index.ts, src/ui/Navigation/Navigation.styles.tsx, src/ui/Navigation/Navigation.tsx, src/ui/Navigation/components/Drawer/Drawer.tsx, src/ui/Navigation/components/Drawer/Navigation/Navigation.tsx, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.tsx, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/hooks.ts, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/index.ts, src/ui/Navigation/components/GlobalNav/GlobalNav.styles.ts, src/ui/Navigation/components/GlobalNav/GlobalNav.tsx, src/ui/Navigation/components/GlobalNav/index.ts, src/ui/Navigation/index.ts, src/ui/Navigation/types.ts, src/ui/TopBar/TopBar.tsx, src/ui/TopBar/index.ts, src/ui/index.ts
This PR reworks some parts of the code in order to improve rendering efficiency.
This means that some new components were introduced in order to better isolate concerns and push rerenders to leaves as much as possible
[DSTRBTN-540]: https://orfium.atlassian.net/browse/DSTRBTN-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: optimisation improvements

src/utils/RedirectWithStatePassthrough/RedirectWithStatePassthrough.tsx, src/utils/RedirectWithStatePassthrough/index.ts, src/utils/index.ts
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request introduces a new utility function `RedirectWithStatePassthrough` that allows for redirection while preserving the history state. This is useful in scenarios where you want to redirect the user to a new route, but also want to maintain the history state of the current route.
> 
> ## What changed
> A new file `RedirectWithStatePassthrough.tsx` was added in the `utils` directory. This file exports a function `RedirectWithStatePassthrough` that wraps the `Redirect` component from `react-router-dom` and passes through the current location state to the new route.
> 
> The `RedirectWithStatePassthrough` function was also …
=> feat: implement a new utility component

documentation/docs/api/_type-definitions/NavigationProps.md, documentation/docs/api/components/Navigation.mdx, documentation/docs/api/components/RedirectWithStatePassthrough.mdx, documentation/docs/api/components/TopBar.mdx, documentation/docs/api/interfaces/AxiosRequestConfig.md, documentation/docs/api/interfaces/AxiosStatic.md, documentation/docs/api/modules.md
Updates the docs
[DSTRBTN-540]: https://orfium.atlassian.net/browse/DSTRBTN-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update documentation

documentation/docs/api/components/LinkWithStatePassthrough.mdx, documentation/docs/api/components/NavLinkWithStatePassthrough.mdx, documentation/docs/api/components/Navigation.mdx, documentation/docs/api/components/RedirectWithStatePassthrough.mdx, src/index.ts, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.styles.ts, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.tsx, src/utils/LinkWithStatePassthrough/LinkWithStatePassthrough.tsx, src/utils/LinkWithStatePassthrough/index.ts, src/utils/NavLinkWithStatePassthrough/NavLinkWithStatePassthrough.tsx, src/utils/NavLinkWithStatePassthrough/index.ts, src/utils/index.ts
=> feat: implement extra utility components

.github/workflows/pr.yml, documentation/docs/api/Components/LinkWithStatePassthrough.mdx, documentation/docs/api/Components/NavLinkWithStatePassthrough.mdx, documentation/docs/api/Components/Navigation.mdx, documentation/docs/api/Components/RedirectWithStatePassthrough.mdx, documentation/docs/api/Components/Toolbox.mdx, documentation/docs/api/Components/TopBar.mdx, documentation/docs/api/Hooks/useAuthentication.mdx, documentation/docs/api/Hooks/useData.md, documentation/docs/api/Hooks/useDataPagination.md, documentation/docs/api/Hooks/useDeferredValue.md, documentation/docs/api/Hooks/useOrfiumProducts.mdx, documentation/docs/api/Hooks/useOrganizations.mdx, documentation/docs/api/Hooks/useSafeContext.md, documentation/docs/api/Hooks/useSafeDispatch.md, documentation/docs/api/Hooks/useTopBarUtilitySection.mdx, documentation/docs/api/Utilities/Constants/DEFAULT_NAVBAR_HEIGHT.md, documentation/docs/api/Utilities/Functions/00-Currencies/formatToAUD.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToCAD.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToCNY.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToCurrency.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToEUR.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToGBP.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToJPY.mdx, documentation/docs/api/Utilities/Functions/00-Currencies/formatToUSD.mdx, documentation/docs/api/Utilities/Functions/generateRoutes.mdx, documentation/docs/api/Utilities/Singletons/orfiumIdBaseInstance.md, documentation/docs/tutorials/01-Installation and Usage/Requests/index.md, documentation/docusaurus.config.js, documentation/src/css/custom.css
=> feat: branded documentation

.github/workflows/ci.yml
=> fix: semantic-release cannot push the version tag to the branch master

.github/workflows/ci.yml
Adding `id-token` and `packages` permissions for teardown and release
=> chore: adding id-token and packages for permissions

documentation/docs/api/Components/LinkWithStatePassthrough.mdx, documentation/docs/api/Components/NavLinkWithStatePassthrough.mdx, documentation/docs/api/Components/Navigation.mdx, documentation/docs/api/Components/RedirectWithStatePassthrough.mdx, documentation/docs/api/Components/TopBar.mdx
=> chore: update docs

src/contexts/index.ts
=> fix: add missing exports

src/providers/Authentication.tsx, src/providers/Toolbox/Toolbox.tsx
=> feat: add proper dependency arrays to Authentication effect functions

src/ui/Navigation/Navigation.tsx, src/ui/TopBar/TopBar.tsx
Adjust breakoint for small screens from 1200px to 1366ox
https://www.figma.com/file/3deO7jGtkly8ij4TiIUpzY/DS-%7C-V4.5-%5BCurrent-Version%5D?type=design&node-id=15955-1355&mode=design&t=luSpF1vuz9nnZqxa-0
=> fix: adjust breakpoint for small screens from 1200 to 1366

src/ui/Navigation/components/ClientSelector/index.ts, src/ui/Navigation/components/Drawer/Drawer.styles.ts, src/ui/Navigation/components/Drawer/Drawer.tsx, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.styles.ts, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.tsx, src/ui/Navigation/components/OrganizationSelector/index.ts, src/ui/TopBar/components/FancyUserMenu/UserMenu.styles.ts, src/ui/TopBar/components/FancyUserMenu/UserMenu.tsx, src/ui/TopBar/components/FancyUserMenu/index.ts, src/ui/TopBar/components/UserMenu/UserMenu.tsx
=> chore: update based on design team's feedback

src/ui/Navigation/components/Drawer/Drawer.styles.ts, src/ui/Navigation/components/Drawer/Drawer.tsx, src/ui/Navigation/components/GlobalNav/GlobalNav.styles.ts, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.styles.ts, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.tsx
=> chore: implement changes based on design team fedback

src/ui/Scaffold/Scaffold.styles.ts, src/ui/Scaffold/Scaffold.tsx, src/ui/TopBar/TopBar.styles.ts, src/ui/TopBar/TopBar.tsx
=> chore: streamline Scaffold defaults

src/ui/Navigation/components/Drawer/Drawer.styles.ts, src/ui/Navigation/components/Drawer/Drawer.tsx, src/ui/Navigation/components/Drawer/Navigation/Navigation.styles.ts, src/ui/Navigation/components/Drawer/Navigation/Navigation.tsx
=> feat: implement sidebar changes based on dqa and handle scrolling

src/providers/Authentication.tsx
=> chore: delete unused state in Authentication provider

yarn.lock
This PR was created by the Combine PRs action by combining the following PRs:
closes #136 build(deps): bump @babel/traverse from 7.19.6 to 7.24.0 dependabot/npm_and_yarn/babel/traverse-7.24.0
closes #135 build(deps): bump @adobe/css-tools from 4.3.1 to 4.3.3 dependabot/npm_and_yarn/adobe/css-tools-4.3.3
closes #134 build(deps): bump ip from 2.0.0 to 2.0.1 dependabot/npm_and_yarn/ip-2.0.1
=> feat: Combined PR

src/request/createAPIInstance.ts
=> fix: axios type import

package.json, yarn.lock
=> fix: typedoc latest

src/ui/Navigation/components/GlobalNav/GlobalNav.tsx
=> fix: correct svg dimensions in global sidenav

src/ui/Navigation/components/GlobalNav/GlobalNav.tsx
Resolves active breaking bug in production [DVP-246]
[DVP-246]: https://orfium.atlassian.net/browse/DVP-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add missing icons to global nav

src/ui/Navigation/components/GlobalNav/GlobalNav.tsx
=> fix: add test ids to global nav

src/ui/Navigation/components/GlobalNav/GlobalNav.tsx
=> chore: rename test ids to global nav

src/ui/FlippableArrow/FlippableArrow.styles.ts, src/ui/Navigation/common.styles.ts, src/ui/Navigation/components/Drawer/Drawer.styles.ts, src/ui/Navigation/components/Drawer/Navigation/Navigation.styles.ts, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.styles.ts, src/ui/Navigation/components/Drawer/Navigation/components/MenuItem/MenuItem.tsx, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.styles.ts, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.tsx, src/ui/TopBar/TopBar.styles.ts, src/ui/TopBar/components/FancyUserMenu/UserMenu.styles.ts, src/ui/TopBar/components/UserMenu/UserMenu.styles.ts
This fixes consumer issues with both vitest >= 1.5 and remix. While the previous behaviour can be achieved with a config change in vitest, this is the more correct approach for the fix. https://github.com/vitest-dev/vitest/issues/5555
=> fix: add missing file extensions to undocumented imports from ictinus

src/ui/Navigation/components/GlobalNav/GlobalNav.tsx
=> fix: gracefully handle unknown product codes

documentation/yarn.lock, yarn.lock
This PR was created by the Combine PRs action by combining the following PRs:
closes #142 build(deps): bump follow-redirects from 1.15.5 to 1.15.6 in /documentation dependabot/npm_and_yarn/documentation/follow-redirects-1.15.6
closes #141 build(deps): bump follow-redirects from 1.15.5 to 1.15.6 dependabot/npm_and_yarn/follow-redirects-1.15.6
=> Combined PR

src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.tsx, src/ui/TopBar/components/FancyUserMenu/UserMenu.styles.ts, src/ui/TopBar/components/UserMenu/UserMenu.tsx
This PR fixes the logout action of the menu
=> fix(menu): logout action

documentation/package.json, documentation/yarn.lock
This reverts commit 023483a because the docusaurus somehow breaks the links
=> Revert "chore: fix dependencies of documentation" 

documentation/package.json, documentation/yarn.lock, vite.config.ts
This PR fixes an error that builds with watch mode on all modes. Now it passes the correct `false` value if not production.
Also deployed for testing on `[3.0.5-rc.1](https://www.npmjs.com/package/@orfium/toolbox/v/3.0.5-rc.1)`
=> fix: watch on production

package.json, src/ui/Navigation/components/OrganizationSelector/OrganizationSelector.tsx, yarn.lock
[Ticket](https://orfium.atlassian.net/browse/SYN-1690)
=> [SYN-1690] fix: org selection dropdown
